trigger:
- main

pool:
 name: 'pyhton-pool'

steps:
- script: |
    python -m venv .venv
    . .venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Set up Python environment and install dependencies'

- script: |
    . .venv/bin/activate
    FLASK_APP=run.py flask run --host=0.0.0.0 &
    sleep 20  # Wait for Flask app to start
    netstat -tuln  # Check listening ports for debugging
  displayName: 'Start Flask application'

- script: |
    . .venv/bin/activate
    curl -b cookie.txt -d'username=admin&password=admin' http://localhost:5000/login
    curl -c cookie.txt http://localhost:5000/grep_processes?name=kworker
    curl -c cookie.txt "http://localhost:5000/grep_processes?name=xxx%20%26%26%20touch%20%2Ftmp%2Fpwnd"
  displayName: 'Run basic tests'

- script: |
    . .venv/bin/activate
    kill $(jobs -p)  # Stop Flask app
  displayName: 'Stop Flask application'

- script: |
    . .venv/bin/activate
    pip install flake8
    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  displayName: 'Run flake8 for linting'
