trigger:
- main

pool:
  name: 'php-flask-webgoat'

stages:
  - stage: 'build_stage'
    jobs:
      - job: "build"
        steps:
         - script: |
              sudo apt-get update
              sudo apt-get install -y python3.9 python3.9-venv python3.9-distutils curl

              # Download get-pip.py to install pip
              curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

              # Install pip for Python 3.9
              python3.9 get-pip.py

              # Upgrade pip, setuptools, and wheel
              python3.9 -m pip install --upgrade pip setuptools wheel
           displayName: 'Install Python and pip'
           
         - script: |
              python3.9 -m venv .venv
              . .venv/bin/activate
              pip install -r requirements.txt
           displayName: 'Set up virtual environment and run Flask app'
          
         - script: |
             flake8 .
           displayName: 'flake8 finished'

         - script: |
              pytest
           displayName: 'pytest'
