trigger:
- main

pool:
  name: 'pyhton-pool'

steps:
# activating virtual environment

- script: python -m venv .venv
  displayName: 'create virtual environment'

- script: |
    python -m venv .venv
    . .venv/bin/activate
    pip install -r requirements.txt
    FLASK_APP=run.py flask run

- script: |
    . .venv/bin/activate
    pip install flake8
    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  displayName: 'Run flake8 for linting'
