trigger:
- main

pool:
  name: 'php-flask-webgoat'

stages:
  - stage: 'build_stage'
    jobs:
      - job: "build"
        steps:
        
         - script: |
               # Download get-pip.py to install pip
                curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

                # Install pip for Python 3.9
                python3.9 get-pip.py

                # Upgrade pip, setuptools, and wheel
                python3.9 -m pip install --upgrade pip setuptools wheel
           displayName: 'pip installed'
         - script: |
                sudo apt install python3.9 -m venv .venv
                . .venv/bin/activate
                pip install -r requirements.txt
                FLASK_APP=run.py flask run
           displayName: 'build finished'  