trigger:
- main

pool:
  name: 'pyhton-pool'

stages:
  - stage: 'build_stage'
    jobs:
      - job: "build"
        steps:
         - task: UsePythonVersion@0
           inputs:
             versionSpec: '3.x'
             architecture: 'x64'
         - script: |
             python -m pip install --upgrade pip setuptools wheel
           displayName: 'pip installed'
         - script: |
             pip install -r requirements.txt
           displayName: 'build finished'  